### PR TITLE
"Next level in" under lbExpHour

### PR DESCRIPTION
**Pull request by Mineroboter**
Shows how long does it take for the next level. (under lbExpHour)

### CODE REVIEW

**Comment by Novalys** [comment]
Just a FYI, I really appreciate the work done here, I'm currently out of town for the weekend and will check on this as soon as I'm back. Please don't feel like your work is being ignored. Thanks!

**Comment by Wyn10** [comment]
Quick check, you forgot to add it to groupbox3 and make a definition for it.  Both in MainForm.Designer.cs

**Comment by Mineroboter** [comment]
@Wyn10 
Thanks, i have added it, but what do you mean with definition?
I think you mean the default Text, right? When the form is loaded:
`lbTimeNextLevel.Text = string.Empty;`
So it doesn't matter.

**Comment by Wyn10** [comment]
@Mineroboter I meant the label is missing after [#462](https://github.com/Mineroboter/PokemonGo-Bot-SimpleGUI/blob/TimeNextLevel/PokemonGo.RocketAPI.GUI/MainForm.Designer.cs#L462), it needs to be declared.

**Comment by Mineroboter** [comment]
@Wyn10 
Ok, know I understand what you mean. I don't know how I could forget that.

**Comment by mich3lam** [comment]
@Mineroboter It's indeed a great addon. but it's shown as lbTimeNextLevel before you start the bot,.. it's should be unvisible until bot it started like other settings.. fix it<3

**Comment by Mineroboter** [comment]
@mich3lam 
I fixed it. I didn't really used GitHub much, so I just copied things from VS2015 to GitHub and in the progress I forgot some things.

**Comment by mich3lam** [comment]
@Mineroboter  :)

**Comment by Novalys** [comment]
It seems there are some conflicts with the current master could you check that out? I'll be available to merge right away when this is done.

**Pull request closed without merging**
