### PR TITLE
Added Transfer button to Pokemon Form

### PR DESCRIPTION
**Pull request by Versified**
Before: http://prntscr.com/by3t6v

After: http://prntscr.com/by3tf6

### CODE REVIEW

**Comment by dosenhosenjoe** [comment]
Can you transfer multiple pokemon at once with this ?

**Comment by Versified** [comment]
no, just one at a time.

**Comment by dosenhosenjoe** [comment]
Add pl0x ? :D Its annyoing when its transferring pokemon you wanted to keep

**Comment by Versified** [comment]
Maybe later

**Comment by A-VORONKIN** [comment]
Evolve button also will be greate.

**Comment by Novalys** [comment]
Cool stuff, thank you!!

**Pull request merged**
