### PR TITLE
lbCanEvolveCont Enabled

### PR DESCRIPTION
**Pull request by Mineroboter**
When the bot starts the label "can evolve" wasn't disabled like the upper checkbox, so it looks strange.

### CODE REVIEW

**Comment by Novalys** [comment]
Thanks, let me get to the apartment to review and merge!

**Comment by Mineroboter** [comment]
Take your time :)

**Comment by Novalys** [comment]
Just a FYI, I really appreciate the work done here, I'm currently out of town for the weekend and will check on this as soon as I'm back. Please don't feel like your work is being ignored. Thanks!

**Comment by Novalys** [comment]
It seems there are some conflicts with the current master could you check that out? I'll be available to merge right away when this is done.

**Comment by Mineroboter** [comment]
These conflicts started after you merged https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/pull/63 . So I'll check it.

**Pull request closed without merging**
