### PR TITLE
Added "My Pokemon List"

### PR DESCRIPTION
**Pull request by Versified**
Taken from an updated version of my old "My pokemon List" thing.

### CODE REVIEW

**Comment by Versified** [comment]
Preview: http://prntscr.com/by22js

**Comment by Novalys** [comment]
Pretty neat! Wasn't expecting this at all when I saw the title lol thank you for this contribution I'm sure everyone will love it!

**Comment by Versified** [comment]
thanks.

I'm going to make it to show IV too.

**Comment by Novalys** [comment]
Oh if you want to hold like 5 minutes, I was just going to do some minor tweaks to your commit like icon display, etc.. I'll push the change so it doesn't collide with your development.

**Comment by Versified** [comment]
Oh, well it's literally just one line if you wanna add it into your commit too.
 Line 73:
`listViewItem.Text = string.Format("{0}\nCp: {1}\nIV: {2}", pokemon.PokemonId, pokemon.Cp, Math.Floor(Logic.Logic.CalculatePokemonPerfection(pokemon)));`

However, this makes it to the text doesn't fit correctly in which I'm not sure how to fix.

Maybe you know? http://prntscr.com/by272a

**Comment by Novalys** [comment]
Sure thing, let me get that into the commit then, I'll find a way. Thanks!

**Comment by Versified** [comment]
Alright, good luck!

**Comment by Novalys** [comment]
It's done, I basically just fixed some stuff, like you don't really need to create a whole new client instance as we can easily pass the we are using in the main view and changed the way the images were getting retrieved (which by the way is a great method we can use in other parts of the UI, thanks for that!) so it doesn't lock the interface while loading them, let me know if the changes are OK with you. Thanks!

**Comment by Versified** [comment]
Yeah these are great, I should've though about doing some of these.

**Pull request merged**
