### PR TITLE
Change font sizes from 15.75 to 12 (On win 10, lay out was messed up)…

### PR DESCRIPTION
**Pull request by JordyGitHub**
…. Set auto focus to enter username at start up and console box will display two lines instead of one

### CODE REVIEW

**Comment by Novalys** [comment]
The problem is not with the fonts, I changed the scaling to DPI in the latest commit, can you try that one?

**Comment by JordyGitHub** [comment]
Ah, I see.. My DPI was set to 175%, no wonder it looked that huge. I will revert the font size changes. The other changes are useful to take over :)

**Comment by JordyGitHub** [comment]
Done. Nice job btw with the new layout. One thing though, the console box is always on top and doesn't go away (unless you close it)

**Comment by Novalys** [comment]
Fixed the problem with the console, now it's not always on top.

**Pull request closed without merging**
