### PR TITLE
Transfer, update and evolve pokemon from within the pokemon bag

### PR DESCRIPTION
**Pull request by JordyGitHub**
Insert newline in front instead of at the end when logging to loggingbox 
Added 3 useful locations (https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/issues/154)
Added transfer, update and evolve pokemon from within the pokemon bag

 - note, there are quite some commits, but some of my commits were added differently by Novalys, so I took his implementation rather than mine.

### CODE REVIEW

**Comment by alifiana** [comment]
Please added auto recycle items

**Comment by Simpuhl** [comment]
Please merge this soon, been waiting for this feature for a while and checking everyday

**Comment by Novalys** [comment]
@JordyGitHub I'm sorry it seems some of the changes I made created conflicts with the pull request, could you fix them so I can merge this as soon as possible? It's a highly requested feature :smile:

**Comment by JordyGitHub** [comment]
Should be fine now

**Comment by Novalys** [comment]
That was fast! Thanks!

**Comment by Simpuhl** [comment]
I don't see it in the latest release. 

When I bring up pokemon list/bag it's not there.

**Comment by JordyGitHub** [comment]
Ah I see, then @Novalys needs to create a new release for you guys to download.

**Comment by JordyGitHub** [comment]
I create a build based on the latest repo of @Novalys : [PoGo-SimpleGUI_v1.5+.zip](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/396219/PoGo-SimpleGUI_v1.5.zip)

For the official release, you must wait :)

**Pull request merged**
