### PR TITLE
Added Use Incense Button

### PR DESCRIPTION
**Pull request by Versified**

### CODE REVIEW

**Comment by Novalys** [comment]
Good work! Thanks for the contribution.

**Comment by Versified** [comment]
Thanks man =) I really like your bot and thought why not help out y'know :+1:

**Comment by JordyGitHub** [comment]
@Versified does it work using "ItemExpBoost"? I created the implementation myself as well (on my forked branch) but I added another Task in RocketAPI/Client.cs that uses "Type = (int)RequestType.USE_INCENSE," instead of Type = (int)RequestType.USE_ITEM_XP_BOOST,
The incense count went down when I tried to use an incense (on my implementation), does it do the same on yours? If so, cool that you can use client.UseItemExpBoost for using incense :)

**Comment by JordyGitHub** [comment]
I've just tested your implementation but the button itself is disabled. 
After enabling it, it sadly doesn't work. I'm creating a fix (based on my forked branch) in order to get it working :)

**Comment by Versified** [comment]
Mine worked perfectly?

**Comment by Versified** [comment]
Well I tested it one time and it seemed to work, but thanks.

**Pull request merged**
