### PR TITLE
Fixed display of bag sizes on console window

### PR DESCRIPTION
**Pull request by nxy**

### CODE REVIEW

**Comment by Versified** [comment]
I never intended the Pokemon List to be maximizable :laughing:

**Comment by Simpuhl** [comment]
lets merge and release a new version

**Comment by nxy** [comment]
sortmenu

**Comment by Wyn10** [comment]
@nxy Could sorting by Pokedex ID be added?

**Comment by JordyGitHub** [comment]
@nxy I've created another cool addition to the "My  pokemon list": 
niceaddition

**Comment by nxy** [comment]
@JordyGitHub Neat. :+1:

**Comment by Simpuhl** [comment]
Looks beautiful, can't wait for it to go live. 

Can we some how add there IV level to be displayed next to cP?

**Comment by Novalys** [comment]
@JordyGitHub that's really great, do yo intend to share that with everyone? Can you create a pull request?

**Comment by JordyGitHub** [comment]
@Novalys, done: https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/pull/191

**Comment by Simpuhl** [comment]
When can we see @JordyGitHub feature added?

**Comment by Simpuhl** [comment]
@JordyGitHub when will this be in the release?

**Comment by JordyGitHub** [comment]
@Novalys needs to create a new release for you guys to download.

**Comment by JordyGitHub** [comment]
I create a build based on the latest repo of @Novalys : [PoGo-SimpleGUI_v1.5+.zip](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/396219/PoGo-SimpleGUI_v1.5.zip)

For the official release, you must wait :)

**Pull request merged**
