### PR TITLE
Only transfer pokemon below set iv AND cp

### PR DESCRIPTION
**Pull request by JordyGitHub**
added check for cp

### CODE REVIEW

**Comment by Versified** [comment]
Yeah with the redundant comment I realized it still does run the code I think.

**Comment by JordyGitHub** [comment]
By calling those functions, the item/Pokemon will actually be transferred. So I wondered why you think it's redundant?

**Comment by Versified** [comment]
Yeah but I thought it was not used because it was part of a variable instead of on it's own?

**Comment by JordyGitHub** [comment]
Oh i see. The "var transfer" is not used indeed. It's only about the call itself, no idea why "transfer" is there...

**Comment by Versified** [comment]
there are many more that do the same thing
`var transfer = await _client.TransferPokemon(duplicatePokemon.Id); // Redundant?`
`var transfer = await _client.RecycleItem((ItemId)item.Item_, item.Count); // Redundant??`
`var useRaspberry = await _client.UseCaptureItem(encounterId, ItemId.ItemRazzBerry, spawnPointId); // Redundant?`
`var useLuckyEgg = await _client.UseItemExpBoost(ItemId.ItemLuckyEgg); // Redundant?`
`var useIncense = await _client.UseItemIncense(ItemId.ItemIncenseOrdinary); // Redundant?`
`var update = await _client.UpdatePlayerLocation(pokeStop.Latitude, pokeStop.Longitude, _settings.DefaultAltitude); // Redundant?
`var update = await _client.UpdatePlayerLocation(pokemon.Latitude, pokemon.Longitude, _settings.DefaultAltitude); // Redundant?`

**Comment by Versified** [comment]
I just commented it redundant because I was unsure.

**Comment by Novalys** [comment]
I wasn't too sure if merge this because currently there is no way to update the KeepMinCP or KeepMinIV values from the GUI and the direction I want to keep is that you don't need Visual Studio to modify settings files, but I'm pretty positive today I'll be able to finally implement the settings panel. So, here we go! Thank you for your contribution!

**Comment by JordyGitHub** [comment]
Great to hear that :D Keep up the positivity!

**Pull request merged**
