### PR TITLE
Auto Recycling and Transferring at full Item/Pokemon inventory and more

### PR DESCRIPTION
**Pull request by Mineroboter**
+Auto Recycling and Transferring at full Item/Pokemon inventory
+Auto Recycling and Transferring enable/disable in the UserSettings
+Custom Item/Pokemon Inventory in the UserSettings(for further implementations)
~Fixing crashing bug (read more https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/pull/68/commits/f84a464e87075067231fb8dfebbc76e9ca998677)
~Fixing logging crash (read more https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/pull/68/commits/b97909dda19c901660c0bf01acf03ab4bd4e589f)
(and https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/pull/47)

### CODE REVIEW

**Comment by Khayalan** [comment]
Is it possible you could add a filter... So we can click on what we want to transfer and which items to recycle... including we can say "Throw away so much pokeballs, that we have 30 left" for example
That would be awesome :)

**Comment by Mineroboter** [comment]
The bot is doing that. He looks into the folllowing and recycles all items to the given number. So you just need to implement that into the UserSettings and later into the SettingsForm (#67), so you can edit in the GUI without changing the code:

ew KeyValuePair(ItemId.ItemUnknown, 0);
new KeyValuePair(ItemId.ItemPokeBall, 20);
new KeyValuePair(ItemId.ItemGreatBall, 20);
new KeyValuePair(ItemId.ItemUltraBall, 50);
new KeyValuePair(ItemId.ItemMasterBall, 100);
new KeyValuePair(ItemId.ItemPotion, 0);
new KeyValuePair(ItemId.ItemSuperPotion, 0);
new KeyValuePair(ItemId.ItemHyperPotion, 20);
new KeyValuePair(ItemId.ItemMaxPotion, 50);
new KeyValuePair(ItemId.ItemRevive, 10);
new KeyValuePair(ItemId.ItemMaxRevive, 50);
new KeyValuePair(ItemId.ItemLuckyEgg, 200);
new KeyValuePair(ItemId.ItemIncenseOrdinary, 100);
new KeyValuePair(ItemId.ItemIncenseSpicy, 100);
new KeyValuePair(ItemId.ItemIncenseCool, 100);
new KeyValuePair(ItemId.ItemIncenseFloral, 100);
new KeyValuePair(ItemId.ItemTroyDisk, 100);
new KeyValuePair(ItemId.ItemXAttack, 100);
new KeyValuePair(ItemId.ItemXDefense, 100);
new KeyValuePair(ItemId.ItemXMiracle, 100);
new KeyValuePair(ItemId.ItemRazzBerry, 200);
new KeyValuePair(ItemId.ItemBlukBerry, 10);
new KeyValuePair(ItemId.ItemNanabBerry, 10);
new KeyValuePair(ItemId.ItemWeparBerry, 30);
new KeyValuePair(ItemId.ItemPinapBerry, 30);
new KeyValuePair(ItemId.ItemSpecialCamera, 100);
new KeyValuePair(ItemId.ItemIncubatorBasicUnlimited, 100);
new KeyValuePair(ItemId.ItemIncubatorBasic, 100);
new KeyValuePair(ItemId.ItemPokemonStorageUpgrade, 100);
new KeyValuePair(ItemId.ItemItemStorageUpgrade, 100);

Transferring is a little bit more difficult, but I would suggest a white- or blacklist into the SettingsForm (#67)

**Comment by mich3lam** [comment]
@Mineroboter it's a great addon indeed but how does this fix the crashing problem

**Comment by Mineroboter** [comment]
@mich3lam I found another crash bug not the one you mean. https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/pull/68/commits/f84a464e87075067231fb8dfebbc76e9ca998677

**Comment by mich3lam** [comment]
@Mineroboter well, 1 less crash bug is good. do u have any idea about the other one?

**Comment by adrscott** [comment]
Nice work here 👍

**Comment by Mineroboter** [comment]
@mich3lam I looked into it but I don't know how to fix it. I think the only thing that could cause that crash is that the servers send an invalid message and the bot can't handle that message.

**Comment by mich3lam** [comment]
@Mineroboter it's somehow fixed in other bots, they do not crash..

**Comment by Mineroboter** [comment]
Maybe @Novalys need to update the Logic and the API (https://github.com/NecronomiconCoding/NecroBot) because there are several commits between this version and the current one.

**Comment by Novalys** [comment]
It seems there are some conflicts with the current master could you check that out? I'll be available to merge right away when this is done.

**Pull request closed without merging**
